application: gift-starter
version: 21
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# End points
- url: /product
  script: product.api.api
- url: /giftstart/api
  script: giftstart.giftstart_api.api
- url: /pay
  script: pay.api.api
- url: /user.*
  script: gs_user.api.api

# OAuth
- url: /oauth-callback/twitter
  script: social.api.twitter_oauth_callback
  secure: always
- url: /oauth-callback/googleplus
  script: social.api.googleplus_oauth_callback
  secure: always

# Client static asset urls
- url: /favicon\.ico
  static_files: client/assets/favicon.ico
  upload: client/assets/favicon\.ico
  secure: always
- url: /stylesheets
  static_dir: client/stylesheets
  secure: always
- url: /scripts
  static_dir: client/scripts
  secure: always
- url: /bower_components
  static_dir: client/bower_components
  secure: always
- url: /assets
  static_dir: client/assets
  secure: always
- url: /templates/angular
  static_dir: client/templates/angular
  secure: always

# Catch all other urls
- url: /create-giftstart
  script: main.app_gsc
  secure: always
- url: /giftstart
  script: main.app_gs
  secure: always
- url: /admin.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /.*
  script: main.app
  secure: always

builtins:
  - admin_redirect: on
  - appstats: on

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: latest

env_variables:
  OAUTHLIB_INSECURE_TRANSPORT: 1