application: gift-starter
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /auth
  script: gs_user.auth
- url: /product
  script: product.api
- url: /giftstart/sync
  script: giftstart.sync_api
- url: /giftstart/api
  script: giftstart.api
- url: /pay
  script: pay.api

# Client static asset urls
- url: /favicon\.ico
  static_files: client/assets/favicon.ico
  upload: client/assets/favicon\.ico
- url: /stylesheets
  static_dir: client/stylesheets
- url: /scripts
  static_dir: client/scripts
- url: /bower_components
  static_dir: client/bower_components
- url: /assets
  static_dir: client/assets
- url: /templates/angular
  static_dir: client/templates/angular

# Catch all other urls
- url: /create-giftstart
  script: main.app_gsc
- url: /giftstart
  script: main.app_gs
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: latest
