application: www-dev-gift-starter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# End points
- url: /product
  script: product.product_api.api
- url: /giftstart/api
  script: giftstart.giftstart_api.api
- url: /giftstart/api/hot-campaigns
  script: giftstart.giftstart_api.hot_campaigns
- url: /pay
  script: pay.pay_api.api
- url: /userstats
  script: gs_user.gs_user_api.stats
- url: /user.*
  script: gs_user.gs_user_api.api
- url: /u
  script: gs_user.gs_user_api.user_page
- url: /reports
  script: reports.handler
  login: admin
- url: /card
  script: card.handler
  login: admin

# Client static asset urls
- url: /favicon\.ico
  static_files: client/assets/favicon.ico
  upload: client/assets/favicon\.ico
  secure: always
- url: /stylesheets
  static_dir: client/stylesheets
  secure: always
- url: /scripts
  static_dir: client/scripts
  secure: always
- url: /bower_components
  static_dir: client/bower_components
  secure: always
- url: /assets
  static_dir: client/assets
  secure: always
- url: /templates/angular
  static_dir: client/templates/angular
  secure: always

# Catch all other urls
- url: /create-giftstart
  script: main.app_gsc
  secure: always
- url: /giftstart
  script: main.app_gs
  secure: always
- url: /admin.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /.*
  script: main.app
  secure: always

builtins:
  - admin_redirect: on
  - appstats: on

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: latest

env_variables:
  OAUTHLIB_INSECURE_TRANSPORT: 1