application: gift-starter
version: 37
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Product
- url: /products/urls/.*.json
  script: product.product_api.handler
- url: /products/.*.json
  script: product.product_api.handler
- url: /product
  script: product.product_api.handler

# GiftStart
- url: /giftstart/api # MAKE RESTful!... Remove?
  script: giftstart.giftstart_api.api
- url: /giftstart/api/hot-campaigns # MAKE RESTful!
  script: giftstart.giftstart_api.hot_campaigns
- url: /create-giftstart # MAKE RESTful!
  script: main.app
  secure: always
- url: /giftstart/share
  script: share.email_share_handler
- url: /giftstart/.*/card
  script: giftstart.giftstart_card.handler
  login: admin
- url: /giftstart/.*.json
  script: giftstart.giftstart_api.handler
  secure: always
- url: /giftstarts.json
  script: giftstart.giftstart_api.handler
  secure: always
- url: /giftstart/.*
  script: main.app
  secure: always

# Pay
- url: /pay
  script: pay.pay_api.api

# Thank
- url: /thanks.*
  script: thank.thank_api.handler

# Users
- url: /users.*
  script: gs_user.gs_user_api.api
- url: /reports
  script: reports.handler
  login: admin

# Login
- url: /login/.*
  script: login.login_api.handler
  secure: always

# Email
- url: /email/.*
  script: gs_email.gs_email_api.handler

# Feeds
- url: /feeds/.*
  script: feeds.feeds_api.handler

# Analytics
- url: /a/.*
  script: analytics.handler
  secure: always

# Client static asset urls
- url: /favicon\.ico
  static_files: client/assets/favicon.ico
  upload: client/assets/favicon\.ico
  secure: always
- url: /stylesheets
  static_dir: client/stylesheets
  secure: always
- url: /scripts
  static_dir: client/scripts
  secure: always
- url: /bower_components
  static_dir: client/bower_components
  secure: always
- url: /assets
  static_dir: client/assets
  secure: always
- url: /templates/angular
  static_dir: client/templates/angular
  secure: always
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
- url: /sitemap-app.xml
  static_files: sitemap-app.xml
  upload: sitemap-app.xml
- url: /googled6c05fd809b457a4.html
  static_files: googled6c05fd809b457a4.html
  upload: googled6c05fd809b457a4.html

# Data dumps
- url: /dump/.*
  script: analytics.handler
  login: admin

# Blog
- url: /blog
  script: blog.handler
  secure: always
- url: /blog/.*
  script: blog.handler
  secure: always
- url: /press
  script: blog.handler
  secure: always
- url: /press/
  script: blog.handler
  secure: always
- url: /wedding.*
  script: blog.handler
  secure: always

# Catch all other urls
- url: /admin.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /.*
  script: main.app
  secure: always

builtins:
  - admin_redirect: on
  - appstats: on

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "2.3"
- name: ssl
  version: latest

env_variables:
  OAUTHLIB_INSECURE_TRANSPORT: 1

skip_files:
- grunt/.*
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- client/stylesheets/^(?!compiled)
- client/test/*
- client/bower_components/*
- client/scripts/^(?!out)
