environment:              'development'
team_notification_email:  'team@giftstarter.com'
product_api_url:          'https://product-dev-gift-starter.appspot.com/static/dev'

app_url:                  'https://www.dev.giftstarter.com'
email_url:                'https://www.dev.giftstarter.com/email/send.json'
storage_url:              '/giftstarter-pictures/dev/'

facebook_app:             'dev-giftstarter'
facebook_app_id:          '336526276498819'

baseServiceFeeRate:       0.08

couponCodes:               ['GiftMe!','CollisionGift','Collision15','StartupGift','GiftFriend','GiftPartner','GiftItForward','9MileLabsGift','Level3Gift','Logic2020Gift','PathwiseGift','ProductHunt8','Yunderson15','GiftMe8','Facebook8','LenatiGift','SurfGift8','TactileGift8','BandHGift','ButterGift','FatCorkGift','SturtevantsGift','GiftAmazingPR','GiftItPR','GiftingPR','GiftsMatterPR','GiftSmarterPR','WeGiftPR','PitchGiftPR','StartGiftPR','SummerGiftPR','JulyGiftPR','AugustGiftPR','SeptemberGiftPR','HolidayGiftPR','SchoolGiftPR','GameGiftPR','BeautyGiftPR','RetailGiftPR','BrandGiftPR','FashionGiftPR','MediaGiftPR']

commonSearchWords:         ['amazon','apple','baby+crib','baby','baby+crib','bag','barbecue+grill','bassinet','battlestar','bicycle','bike','birthday','bose','butter+london','butter+london','camera','car','computer','cradle','crib+bedding','crib+bedding','cuisinart','diaper+bag','dog+bed','duvet','dyson+vacuum','fat+cork','fat+cork','fatcork','fish+tank','fitbit','flower','flowers','frends','gopro','high+chair','high+chair','home+theater','home+theater','icpooch','ipad','iphone','ipod','keurig','lawn+mower','lumix+gh4','macbook','microsoft+office','nikon','phone','playard','playstation','rei','rocking+chair','rug','samsung','shoes','sofa','stroller','sturtevants','t5i','television','toaster+oven','tv','Vitamix','wedding+gifts','wedding','wine','wireless+speaker','Xbox+one','xbox']

googleanalytics:
  key:                    'UA-51616127-7'

mixpanel:
  key:                    '2cfdda518bed5ee0bc7e9ad48c8c8f48'

prosperent:
  key:                    '0ea6828d486ddb94138d277e9007790b'

heap:
  key:                    '4144879771'

cardprocessor:            'paypal'